apiVersion: v1
kind: Service
metadata:
  name: svc-mario-demo
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: mario-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mario-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mario-demo
  template:
    metadata:
      labels:
        app: mario-demo
    spec:
      containers:
      - name: mario-demo
        image: sevenajay/mario:latest 
        resources:
          limits:
            cpu: "1"
            memory: 2G
          requests:
            cpu: "1"
            memory: 1G
        ports:
        - containerPort: 80